### ISSUE TITLE
Add support for using protocol instead of subclassing for model files

### ISSUE THREAD

**Issue by Buju77** [joshdholtz/jsonapi-ios#11]
It would be nice if we don't have to subclass JSONAPIResource for our model files. Because we are subclassing our model files with our own base class already. We could then use this pod if the whole system also supports some kind of protocol. So our model files just simply implements the protocol.

**Comment by joshdholtz** [comment]
I believe I merged changes into this a while back but I need to add more docs on how to do this :) See `JSONAPIResource`. `JSONAPIResourceBase` is an example of a class that uses that protocol.
