### ISSUE TITLE
Add support for converting model files into JSON (NSDictionary)

### ISSUE THREAD

**Issue by Buju77** [joshdholtz/jsonapi-ios#12]
Currently this pod only supports converting in one way: Json Dictionary/String --> Model

But for it to really be useful, it should also provide the other way around: Model --> Json Dictionary/String

**Comment by jkarmstr** [comment]
My fork has both 2 way support and protocol based resource definition. It's diverged quite a bit from this base.

**Comment by joshdholtz** [comment]
@jkarmstr My apologies! I completely forgot about the PR :pensive: I will look into it this weekend!

**Comment by jkarmstr** [comment]
Fair warning; It's a fairly different implementation at this point. Your project was a good starting point, and the structure of it is still mostly there, but I'm not sure it's easily merged at this point.
