### ISSUE TITLE
Needs updating to support JSON API v1.0 (final)

### ISSUE THREAD

**Issue by mharper** [joshdholtz/jsonapi-ios#14]
Does not appear to support JSON API v1.0 (final).  Here's a similar commit in a related project to support late breaking changes in the spec:

https://github.com/wvteijlingen/Spine/commit/5c12c6223a6ea6cd076054e81a58b3ccf0504afb

**Comment by developer-anreal** [comment]
+1 for this request.
As I understand, there is one obj-c implementation for JSON API.
Spine swift-only.
Because of using v1.0 final on backend this lib does not work :(

**Comment by joshdholtz** [comment]
@mharper @developer-anreal Sorry about that :pensive: I will work on getting this change in tonight for you both... I will ping both of you when its up

**Comment by developer-anreal** [comment]
@joshdholtz thank you.
I will wait with impatience your notification.

**Comment by developer-anreal** [comment]
Hello!
Thank you for adopting your lib for JSONAPI 1.0 spec.
But I have one more question related to objects mapping.
After I create resource I found that relationship objects are empty(but not nil). ID field is set but other instance variables are nil.
But *includedResources* variable in JSONAPI object contains objects I mentioned above with all variables filled correctly.
So, can I work only with subclass of *JSONAPIResourceBase* and get relationship resources without JSONAPI object?
