### ISSUE TITLE
Wrong getter for ID property

### ISSUE THREAD

**Issue by turbokuzmich** [joshdholtz/jsonapi-ios#17]
Found several places where resource ID property is referenced this way:
```objc
resource.ID
```
Suppose that the correct way would be:
```objc
JSONAPIResourceDescriptor *desc = <get resource descriptor somehow>;
...
[[resource valueForKey:desc.idProperty] blah];
```

**Comment by joshdholtz** [comment]
@turbokuzmich I don't think I follow what the issue is 100% :innocent: Would you be able to give a different example?

**Comment by joshdholtz** [comment]
Or link to specific places?

**Comment by joshdholtz** [comment]
No more info so closing
