### ISSUE TITLE
Error: Cannot find interface declaration for NSObject in JSONAPIErrorResource.h (Xcode 7)

### ISSUE THREAD

**Issue by ilTofa** [joshdholtz/jsonapi-ios#22]
I got this error while using the library "as-is" (no CocoaPods) with Xcode 7. The error _could_ be coming from the absence of .pch file in the project.

The error can be fixed by adding the declarations for NSObject to the offending header. 
i.e.: adding
```
@import Foundation;
```
to JSONAPIErrorResource.h

**Comment by joshdholtz** [comment]
@ilTofa Sorry about just seeing this issue! Must have missed this in my inbox :pensive: This should get fixed in #26 and I will be pushing a new version out to CocoaPods today for you with this
