### ISSUE TITLE
encoding & decoding

### ISSUE THREAD

**Issue by ionutsebastian824** [joshdholtz/jsonapi-ios#40]
does it support or should I manually handle it with dictionary?

**Comment by joshdholtz** [comment]
@ionutsebastian824 I am not exactly sure what you are asking 😇 Can you provide some more detail or an example?

**Comment by ionutsebastian824** [comment]
@joshdholtz I meant serialization ;)

**Comment by joshdholtz** [comment]
@ionutsebastian824 The library does support some serialization for communicating back up to the API. Some examples can be seen here - https://github.com/joshdholtz/jsonapi-ios/blob/master/Project/JSONAPITests/JSONAPITests.m#L127-L184

**Comment by ionutsebastian824** [comment]
I was going to store object to NSUserDefaults after archive using NSKeyedArchiver but it crashed

**Comment by joshdholtz** [comment]
Ahhh, like that... I didn't know you meant storing to disc 😉 I thought you meant posting data back up to an API... Yeah, I don't think that is built in??? You may need to write custom stuff for that 😬

**Comment by ionutsebastian824** [comment]
ok, appreciate for your response 👍
