### ISSUE TITLE
Resource metadata

### ISSUE THREAD

**Issue by alessandro-shore** [joshdholtz/jsonapi-ios#42]
Is there any way to access the meta object of an included resource: 

`  "included": [
    {
      "meta":  {
               "unresolved": "This is a test message"
               },
      "id": "93ae7543-3ae1-417f-8feb-51217b5f4d01",
      "type": "participants"
    },`

I've tried adding "meta" as a property and as a "hasOne" relationship, but that didn't work.

Thank you

**Comment by joshdholtz** [comment]
@alessandro-shore I will work on adding that right now! I was not aware that `meta` was an optional attribute but I will add that right now 😊

**Comment by joshdholtz** [comment]
@alessandro-shore You should be able to access the meta with version `1.0.7` ✊ 

``` ruby
pod 'JSONAPI', '~> 1.0.7'
```

**Comment by alessandro-shore** [comment]
Awesome! Thank you very much!
