### ISSUE TITLE
JSON API RC3 tracking

### ISSUE THREAD

**Issue by steveklabnik** [joshdholtz/jsonapi-ios#8]
Hey there! I just wanted to let you know that JSON API has hit RC3, and we'd like client libraries to start implementing it like it was 1.0, as a final check that we're good for 1.0. I wanted to make this issue to let you know!

https://github.com/json-api/json-api/issues/484

**Comment by joshdholtz** [comment]
@steveklabnik Hey! I got stuff started right here already - https://github.com/joshdholtz/jsonapi-ios/tree/0.3.0-json-api-spec-updates. I'm actually going on vacation tomorrow for a week so this will be a perfect time for me to finish updating my library :grin: 

I will let ya know when everything is :+1:

**Comment by steveklabnik** [comment]
Oh awesome :+1: 

Sorry about the changes that's happened, there was a ton of tiny things :( But we're almost out of the woods!

**Comment by joshdholtz** [comment]
Ah, no problem at all! I like changes. It usually means people care about it. I like working on things that people care about :blush:

**Comment by steveklabnik** [comment]
I am the _exact_ same way.

**Comment by joshdholtz** [comment]
@steveklabnik Made the changes! Not sure if you would like to review it but thought I would give you an option if you do :grin:
